# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoGitCommitsAuthor do
  @moduledoc """
  Information about the author of the commit. By default, the `author` will be the authenticated user and the current date. See the `author` and `committer` object below for details.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :email,
    :date
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :email => String.t(),
          :date => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ReposOwnerRepoGitCommitsAuthor do
  def decode(value, _options) do
    value
  end
end
