# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoBranchesBranchProtectionRestrictions do
  @moduledoc """
  Restrict who can push to the protected branch. User, app, and team `restrictions` are only available for organization-owned repositories. Set to `null` to disable.
  """

  @derive [Poison.Encoder]
  defstruct [
    :users,
    :teams,
    :apps
  ]

  @type t :: %__MODULE__{
          :users => [String.t()],
          :teams => [String.t()],
          :apps => [String.t()] | nil
        }
end

defimpl Poison.Decoder,
  for: GitHubV3RESTAPI.Model.ReposOwnerRepoBranchesBranchProtectionRestrictions do
  def decode(value, _options) do
    value
  end
end
