# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoGitTreesTree do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :path,
    :mode,
    :type,
    :sha,
    :content
  ]

  @type t :: %__MODULE__{
          :path => String.t() | nil,
          :mode => String.t() | nil,
          :type => String.t() | nil,
          :sha => String.t() | nil,
          :content => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ReposOwnerRepoGitTreesTree do
  def decode(value, _options) do
    value
  end
end
