# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoHooksConfig do
  @moduledoc """
  Key/value pairs to provide settings for this webhook. [These are defined below](https://docs.github.com/rest/reference/repos#create-hook-config-params).
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :content_type,
    :secret,
    :insecure_ssl,
    :token,
    :digest
  ]

  @type t :: %__MODULE__{
          :url => String.t() | nil,
          :content_type => String.t() | nil,
          :secret => String.t() | nil,
          :insecure_ssl => GitHubV3RESTAPI.Model.WebhookConfigInsecureSsl.t() | nil,
          :token => String.t() | nil,
          :digest => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ReposOwnerRepoHooksConfig do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :insecure_ssl,
      :struct,
      GitHubV3RESTAPI.Model.WebhookConfigInsecureSsl,
      options
    )
  end
end
