# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoContentsPathAuthor1 do
  @moduledoc """
  object containing information about the author.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :email
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :email => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ReposOwnerRepoContentsPathAuthor1 do
  def decode(value, _options) do
    value
  end
end
