# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoCheckSuitesPreferencesAutoTriggerChecks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :app_id,
    :setting
  ]

  @type t :: %__MODULE__{
          :app_id => integer(),
          :setting => boolean()
        }
end

defimpl Poison.Decoder,
  for: GitHubV3RESTAPI.Model.ReposOwnerRepoCheckSuitesPreferencesAutoTriggerChecks do
  def decode(value, _options) do
    value
  end
end
