# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions do
  @moduledoc """
  Specify which users and teams can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories.
  """

  @derive [Poison.Encoder]
  defstruct [
    :users,
    :teams
  ]

  @type t :: %__MODULE__{
          :users => [String.t()] | nil,
          :teams => [String.t()] | nil
        }
end

defimpl Poison.Decoder,
  for:
    GitHubV3RESTAPI.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions do
  def decode(value, _options) do
    value
  end
end
