# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ActionsOrganizationPermissions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :enabled_repositories,
    :selected_repositories_url,
    :allowed_actions,
    :selected_actions_url
  ]

  @type t :: %__MODULE__{
          :enabled_repositories => GitHubV3RESTAPI.Model.EnabledRepositories.t(),
          :selected_repositories_url => String.t() | nil,
          :allowed_actions => GitHubV3RESTAPI.Model.AllowedActions.t() | nil,
          :selected_actions_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ActionsOrganizationPermissions do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :enabled_repositories,
      :struct,
      GitHubV3RESTAPI.Model.EnabledRepositories,
      options
    )
    |> deserialize(:allowed_actions, :struct, GitHubV3RESTAPI.Model.AllowedActions, options)
  end
end
