# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ActionsBillingUsageMinutesUsedBreakdown do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :UBUNTU,
    :MACOS,
    :WINDOWS
  ]

  @type t :: %__MODULE__{
          :UBUNTU => integer() | nil,
          :MACOS => integer() | nil,
          :WINDOWS => integer() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ActionsBillingUsageMinutesUsedBreakdown do
  def decode(value, _options) do
    value
  end
end
