# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Artifact do
  @moduledoc """
  An artifact
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :name,
    :size_in_bytes,
    :url,
    :archive_download_url,
    :expired,
    :created_at,
    :expires_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :name => String.t(),
          :size_in_bytes => integer(),
          :url => String.t(),
          :archive_download_url => String.t(),
          :expired => boolean(),
          :created_at => DateTime.t() | nil,
          :expires_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Artifact do
  def decode(value, _options) do
    value
  end
end
