# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.AuthorAssociation do
  @moduledoc """
  How the author is associated with the repository.
  """

  @derive [Poison.Encoder]
  defstruct []

  @type t :: %__MODULE__{}
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.AuthorAssociation do
  def decode(value, _options) do
    value
  end
end
