# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.BranchProtectionRequiredStatusChecks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :enforcement_level,
    :contexts,
    :contexts_url,
    :strict
  ]

  @type t :: %__MODULE__{
          :url => String.t() | nil,
          :enforcement_level => String.t() | nil,
          :contexts => [String.t()],
          :contexts_url => String.t() | nil,
          :strict => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.BranchProtectionRequiredStatusChecks do
  def decode(value, _options) do
    value
  end
end
