# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.CheckSuitePreferencePreferences do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :auto_trigger_checks
  ]

  @type t :: %__MODULE__{
          :auto_trigger_checks =>
            [GitHubV3RESTAPI.Model.CheckSuitePreferencePreferencesAutoTriggerChecks.t()] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.CheckSuitePreferencePreferences do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :auto_trigger_checks,
      :list,
      GitHubV3RESTAPI.Model.CheckSuitePreferencePreferencesAutoTriggerChecks,
      options
    )
  end
end
