# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.CheckAnnotation do
  @moduledoc """
  Check Annotation
  """

  @derive [Poison.Encoder]
  defstruct [
    :path,
    :start_line,
    :end_line,
    :start_column,
    :end_column,
    :annotation_level,
    :title,
    :message,
    :raw_details,
    :blob_href
  ]

  @type t :: %__MODULE__{
          :path => String.t(),
          :start_line => integer(),
          :end_line => integer(),
          :start_column => integer() | nil,
          :end_column => integer() | nil,
          :annotation_level => String.t() | nil,
          :title => String.t() | nil,
          :message => String.t() | nil,
          :raw_details => String.t() | nil,
          :blob_href => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.CheckAnnotation do
  def decode(value, _options) do
    value
  end
end
