# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.CodeOfConduct do
  @moduledoc """
  Code Of Conduct
  """

  @derive [Poison.Encoder]
  defstruct [
    :key,
    :name,
    :url,
    :body,
    :html_url
  ]

  @type t :: %__MODULE__{
          :key => String.t(),
          :name => String.t(),
          :url => String.t(),
          :body => String.t() | nil,
          :html_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.CodeOfConduct do
  def decode(value, _options) do
    value
  end
end
