# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.CodeScanningAnalysisDeletion do
  @moduledoc """
  Successful deletion of a code scanning analysis
  """

  @derive [Poison.Encoder]
  defstruct [
    :next_analysis_url,
    :confirm_delete_url
  ]

  @type t :: %__MODULE__{
          :next_analysis_url => String.t() | nil,
          :confirm_delete_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.CodeScanningAnalysisDeletion do
  def decode(value, _options) do
    value
  end
end
