# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.CommunityHealthFile do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :html_url
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :html_url => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.CommunityHealthFile do
  def decode(value, _options) do
    value
  end
end
