# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.CommunityProfile do
  @moduledoc """
  Community Profile
  """

  @derive [Poison.Encoder]
  defstruct [
    :health_percentage,
    :description,
    :documentation,
    :files,
    :updated_at,
    :content_reports_enabled
  ]

  @type t :: %__MODULE__{
          :health_percentage => integer(),
          :description => String.t() | nil,
          :documentation => String.t() | nil,
          :files => GitHubV3RESTAPI.Model.CommunityProfileFiles.t(),
          :updated_at => DateTime.t() | nil,
          :content_reports_enabled => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.CommunityProfile do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:files, :struct, GitHubV3RESTAPI.Model.CommunityProfileFiles, options)
  end
end
