# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ContentTraffic do
  @moduledoc """
  Content Traffic
  """

  @derive [Poison.Encoder]
  defstruct [
    :path,
    :title,
    :count,
    :uniques
  ]

  @type t :: %__MODULE__{
          :path => String.t(),
          :title => String.t(),
          :count => integer(),
          :uniques => integer()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ContentTraffic do
  def decode(value, _options) do
    value
  end
end
