# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.DeploymentReviewerType do
  @moduledoc """
  The type of reviewer. Must be one of: `User` or `Team`
  """

  @derive [Poison.Encoder]
  defstruct []

  @type t :: %__MODULE__{}
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.DeploymentReviewerType do
  def decode(value, _options) do
    value
  end
end
