# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Email do
  @moduledoc """
  Email
  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :primary,
    :verified,
    :visibility
  ]

  @type t :: %__MODULE__{
          :email => String.t(),
          :primary => boolean(),
          :verified => boolean(),
          :visibility => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Email do
  def decode(value, _options) do
    value
  end
end
