# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Event do
  @moduledoc """
  Event
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :type,
    :actor,
    :repo,
    :org,
    :payload,
    :public,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :type => String.t() | nil,
          :actor => GitHubV3RESTAPI.Model.Actor.t(),
          :repo => GitHubV3RESTAPI.Model.EventRepo.t(),
          :org => GitHubV3RESTAPI.Model.Actor.t() | nil,
          :payload => GitHubV3RESTAPI.Model.EventPayload.t(),
          :public => boolean(),
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Event do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actor, :struct, GitHubV3RESTAPI.Model.Actor, options)
    |> deserialize(:repo, :struct, GitHubV3RESTAPI.Model.EventRepo, options)
    |> deserialize(:org, :struct, GitHubV3RESTAPI.Model.Actor, options)
    |> deserialize(:payload, :struct, GitHubV3RESTAPI.Model.EventPayload, options)
  end
end
