# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.EventPayloadPages do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :page_name,
    :title,
    :summary,
    :action,
    :sha,
    :html_url
  ]

  @type t :: %__MODULE__{
          :page_name => String.t() | nil,
          :title => String.t() | nil,
          :summary => String.t() | nil,
          :action => String.t() | nil,
          :sha => String.t() | nil,
          :html_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.EventPayloadPages do
  def decode(value, _options) do
    value
  end
end
