# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.FileCommitCommitVerification do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :verified,
    :reason,
    :signature,
    :payload
  ]

  @type t :: %__MODULE__{
          :verified => boolean() | nil,
          :reason => String.t() | nil,
          :signature => String.t() | nil,
          :payload => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.FileCommitCommitVerification do
  def decode(value, _options) do
    value
  end
end
