# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.GistHistoryChangeStatus do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total,
    :additions,
    :deletions
  ]

  @type t :: %__MODULE__{
          :total => integer() | nil,
          :additions => integer() | nil,
          :deletions => integer() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.GistHistoryChangeStatus do
  def decode(value, _options) do
    value
  end
end
