# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.GistSimpleFiles do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :filename,
    :type,
    :language,
    :raw_url,
    :size,
    :truncated,
    :content
  ]

  @type t :: %__MODULE__{
          :filename => String.t() | nil,
          :type => String.t() | nil,
          :language => String.t() | nil,
          :raw_url => String.t() | nil,
          :size => integer() | nil,
          :truncated => boolean() | nil,
          :content => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.GistSimpleFiles do
  def decode(value, _options) do
    value
  end
end
