# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.GitTagObject do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :sha,
    :type,
    :url
  ]

  @type t :: %__MODULE__{
          :sha => String.t(),
          :type => String.t(),
          :url => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.GitTagObject do
  def decode(value, _options) do
    value
  end
end
