# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.GitCommitAuthor do
  @moduledoc """
  Identifying information for the git-user
  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :email,
    :name
  ]

  @type t :: %__MODULE__{
          :date => DateTime.t(),
          :email => String.t(),
          :name => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.GitCommitAuthor do
  def decode(value, _options) do
    value
  end
end
