# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.GpgKeySubkeys do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :primary_key_id,
    :key_id,
    :public_key,
    :emails,
    :subkeys,
    :can_sign,
    :can_encrypt_comms,
    :can_encrypt_storage,
    :can_certify,
    :created_at,
    :expires_at,
    :raw_key
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :primary_key_id => integer() | nil,
          :key_id => String.t() | nil,
          :public_key => String.t() | nil,
          :emails => [AnyType] | nil,
          :subkeys => [AnyType] | nil,
          :can_sign => boolean() | nil,
          :can_encrypt_comms => boolean() | nil,
          :can_encrypt_storage => boolean() | nil,
          :can_certify => boolean() | nil,
          :created_at => String.t() | nil,
          :expires_at => String.t() | nil,
          :raw_key => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.GpgKeySubkeys do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:emails, :list, GitHubV3RESTAPI.Model.AnyType, options)
    |> deserialize(:subkeys, :list, GitHubV3RESTAPI.Model.AnyType, options)
  end
end
