# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.HookResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :status,
    :message
  ]

  @type t :: %__MODULE__{
          :code => integer() | nil,
          :status => String.t() | nil,
          :message => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.HookResponse do
  def decode(value, _options) do
    value
  end
end
