# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.HookDeliveryItem do
  @moduledoc """
  Delivery made by a webhook, without request and response information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :guid,
    :delivered_at,
    :redelivery,
    :duration,
    :status,
    :status_code,
    :event,
    :action,
    :installation_id,
    :repository_id
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :guid => String.t(),
          :delivered_at => DateTime.t(),
          :redelivery => boolean(),
          :duration => float(),
          :status => String.t(),
          :status_code => integer(),
          :event => String.t(),
          :action => String.t() | nil,
          :installation_id => integer() | nil,
          :repository_id => integer() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.HookDeliveryItem do
  def decode(value, _options) do
    value
  end
end
