# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject91 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :config,
    :events,
    :active
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :config => GitHubV3RESTAPI.Model.ReposOwnerRepoHooksConfig.t() | nil,
          :events => [String.t()] | nil,
          :active => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject91 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:config, :struct, GitHubV3RESTAPI.Model.ReposOwnerRepoHooksConfig, options)
  end
end
