# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject60 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :enabled,
    :allowed_actions
  ]

  @type t :: %__MODULE__{
          :enabled => boolean(),
          :allowed_actions => GitHubV3RESTAPI.Model.AllowedActions.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject60 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:allowed_actions, :struct, GitHubV3RESTAPI.Model.AllowedActions, options)
  end
end
