# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineResponse20012 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :installations
  ]

  @type t :: %__MODULE__{
          :total_count => integer(),
          :installations => [GitHubV3RESTAPI.Model.Installation.t()]
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineResponse20012 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:installations, :list, GitHubV3RESTAPI.Model.Installation, options)
  end
end
