# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :repositories,
    :repository_ids,
    :permissions
  ]

  @type t :: %__MODULE__{
          :repositories => [String.t()] | nil,
          :repository_ids => [integer()] | nil,
          :permissions => GitHubV3RESTAPI.Model.AppPermissions.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject1 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:permissions, :struct, GitHubV3RESTAPI.Model.AppPermissions, options)
  end
end
