# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject64 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :key_prefix,
    :url_template
  ]

  @type t :: %__MODULE__{
          :key_prefix => String.t(),
          :url_template => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject64 do
  def decode(value, _options) do
    value
  end
end
