# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject63 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ref,
    :inputs
  ]

  @type t :: %__MODULE__{
          :ref => String.t(),
          :inputs => %{optional(String.t()) => String.t()} | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject63 do
  def decode(value, _options) do
    value
  end
end
