# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject23 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :billing_email,
    :company,
    :email,
    :twitter_username,
    :location,
    :name,
    :description,
    :has_organization_projects,
    :has_repository_projects,
    :default_repository_permission,
    :members_can_create_repositories,
    :members_can_create_internal_repositories,
    :members_can_create_private_repositories,
    :members_can_create_public_repositories,
    :members_allowed_repository_creation_type,
    :members_can_create_pages,
    :members_can_create_public_pages,
    :members_can_create_private_pages,
    :blog
  ]

  @type t :: %__MODULE__{
          :billing_email => String.t() | nil,
          :company => String.t() | nil,
          :email => String.t() | nil,
          :twitter_username => String.t() | nil,
          :location => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :has_organization_projects => boolean() | nil,
          :has_repository_projects => boolean() | nil,
          :default_repository_permission => String.t() | nil,
          :members_can_create_repositories => boolean() | nil,
          :members_can_create_internal_repositories => boolean() | nil,
          :members_can_create_private_repositories => boolean() | nil,
          :members_can_create_public_repositories => boolean() | nil,
          :members_allowed_repository_creation_type => String.t() | nil,
          :members_can_create_pages => boolean() | nil,
          :members_can_create_public_pages => boolean() | nil,
          :members_can_create_private_pages => boolean() | nil,
          :blog => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject23 do
  def decode(value, _options) do
    value
  end
end
