# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject146 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :Operations
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :Operations => [map()]
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject146 do
  def decode(value, _options) do
    value
  end
end
