# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineResponse20014 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :workflow_runs
  ]

  @type t :: %__MODULE__{
          :total_count => integer(),
          :workflow_runs => [GitHubV3RESTAPI.Model.WorkflowRun.t()]
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineResponse20014 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:workflow_runs, :list, GitHubV3RESTAPI.Model.WorkflowRun, options)
  end
end
