# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineResponse403Block do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :reason,
    :created_at,
    :html_url
  ]

  @type t :: %__MODULE__{
          :reason => String.t() | nil,
          :created_at => String.t() | nil,
          :html_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineResponse403Block do
  def decode(value, _options) do
    value
  end
end
