# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject73 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :permission,
    :permissions
  ]

  @type t :: %__MODULE__{
          :permission => String.t() | nil,
          :permissions => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject73 do
  def decode(value, _options) do
    value
  end
end
