# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject111 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :base,
    :head,
    :commit_message
  ]

  @type t :: %__MODULE__{
          :base => String.t(),
          :head => String.t(),
          :commit_message => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject111 do
  def decode(value, _options) do
    value
  end
end
