# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineResponse2004 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :runners
  ]

  @type t :: %__MODULE__{
          :total_count => float() | nil,
          :runners => [GitHubV3RESTAPI.Model.Runner.t()] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineResponse2004 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:runners, :list, GitHubV3RESTAPI.Model.Runner, options)
  end
end
