# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject39 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :description,
    :homepage,
    :private,
    :visibility,
    :has_issues,
    :has_projects,
    :has_wiki,
    :is_template,
    :team_id,
    :auto_init,
    :gitignore_template,
    :license_template,
    :allow_squash_merge,
    :allow_merge_commit,
    :allow_rebase_merge,
    :allow_auto_merge,
    :delete_branch_on_merge
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :description => String.t() | nil,
          :homepage => String.t() | nil,
          :private => boolean() | nil,
          :visibility => String.t() | nil,
          :has_issues => boolean() | nil,
          :has_projects => boolean() | nil,
          :has_wiki => boolean() | nil,
          :is_template => boolean() | nil,
          :team_id => integer() | nil,
          :auto_init => boolean() | nil,
          :gitignore_template => String.t() | nil,
          :license_template => String.t() | nil,
          :allow_squash_merge => boolean() | nil,
          :allow_merge_commit => boolean() | nil,
          :allow_rebase_merge => boolean() | nil,
          :allow_auto_merge => boolean() | nil,
          :delete_branch_on_merge => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject39 do
  def decode(value, _options) do
    value
  end
end
