# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject76 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :body,
    :path,
    :position,
    :line
  ]

  @type t :: %__MODULE__{
          :body => String.t(),
          :path => String.t() | nil,
          :position => integer() | nil,
          :line => integer() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject76 do
  def decode(value, _options) do
    value
  end
end
