# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject147 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :userName,
    :displayName,
    :name,
    :emails,
    :schemas,
    :externalId,
    :groups,
    :active
  ]

  @type t :: %__MODULE__{
          :userName => String.t(),
          :displayName => String.t() | nil,
          :name => GitHubV3RESTAPI.Model.ScimV2OrganizationsOrgUsersName.t(),
          :emails => [GitHubV3RESTAPI.Model.ScimV2OrganizationsOrgUsersEmails.t()],
          :schemas => [String.t()] | nil,
          :externalId => String.t() | nil,
          :groups => [String.t()] | nil,
          :active => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject147 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:name, :struct, GitHubV3RESTAPI.Model.ScimV2OrganizationsOrgUsersName, options)
    |> deserialize(
      :emails,
      :list,
      GitHubV3RESTAPI.Model.ScimV2OrganizationsOrgUsersEmails,
      options
    )
  end
end
