# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject27 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :visibility
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :visibility => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject27 do
  def decode(value, _options) do
    value
  end
end
