# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject51 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :groups
  ]

  @type t :: %__MODULE__{
          :groups =>
            [GitHubV3RESTAPI.Model.OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups.t()] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject51 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :groups,
      :list,
      GitHubV3RESTAPI.Model.OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups,
      options
    )
  end
end
