# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineResponse2001 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :organizations
  ]

  @type t :: %__MODULE__{
          :total_count => float(),
          :organizations => [GitHubV3RESTAPI.Model.OrganizationSimple.t()]
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineResponse2001 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:organizations, :list, GitHubV3RESTAPI.Model.OrganizationSimple, options)
  end
end
