# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject137 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :names
  ]

  @type t :: %__MODULE__{
          :names => [String.t()]
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject137 do
  def decode(value, _options) do
    value
  end
end
