# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject59 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :description,
    :homepage,
    :private,
    :visibility,
    :security_and_analysis,
    :has_issues,
    :has_projects,
    :has_wiki,
    :is_template,
    :default_branch,
    :allow_squash_merge,
    :allow_merge_commit,
    :allow_rebase_merge,
    :allow_auto_merge,
    :delete_branch_on_merge,
    :archived
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :description => String.t() | nil,
          :homepage => String.t() | nil,
          :private => boolean() | nil,
          :visibility => String.t() | nil,
          :security_and_analysis =>
            GitHubV3RESTAPI.Model.ReposOwnerRepoSecurityAndAnalysis.t() | nil,
          :has_issues => boolean() | nil,
          :has_projects => boolean() | nil,
          :has_wiki => boolean() | nil,
          :is_template => boolean() | nil,
          :default_branch => String.t() | nil,
          :allow_squash_merge => boolean() | nil,
          :allow_merge_commit => boolean() | nil,
          :allow_rebase_merge => boolean() | nil,
          :allow_auto_merge => boolean() | nil,
          :delete_branch_on_merge => boolean() | nil,
          :archived => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject59 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :security_and_analysis,
      :struct,
      GitHubV3RESTAPI.Model.ReposOwnerRepoSecurityAndAnalysis,
      options
    )
  end
end
