# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject92 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :events,
    :add_events,
    :remove_events,
    :active
  ]

  @type t :: %__MODULE__{
          :config => GitHubV3RESTAPI.Model.ReposOwnerRepoHooksHookIdConfig.t() | nil,
          :events => [String.t()] | nil,
          :add_events => [String.t()] | nil,
          :remove_events => [String.t()] | nil,
          :active => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject92 do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :config,
      :struct,
      GitHubV3RESTAPI.Model.ReposOwnerRepoHooksHookIdConfig,
      options
    )
  end
end
