# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InlineObject108 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :key,
    :read_only
  ]

  @type t :: %__MODULE__{
          :title => String.t() | nil,
          :key => String.t(),
          :read_only => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InlineObject108 do
  def decode(value, _options) do
    value
  end
end
