# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.InstallationToken do
  @moduledoc """
  Authentication token for a GitHub App installed on a user or org.
  """

  @derive [Poison.Encoder]
  defstruct [
    :token,
    :expires_at,
    :permissions,
    :repository_selection,
    :repositories,
    :single_file,
    :has_multiple_single_files,
    :single_file_paths
  ]

  @type t :: %__MODULE__{
          :token => String.t(),
          :expires_at => String.t(),
          :permissions => GitHubV3RESTAPI.Model.AppPermissions.t() | nil,
          :repository_selection => String.t() | nil,
          :repositories => [GitHubV3RESTAPI.Model.Repository.t()] | nil,
          :single_file => String.t() | nil,
          :has_multiple_single_files => boolean() | nil,
          :single_file_paths => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.InstallationToken do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:permissions, :struct, GitHubV3RESTAPI.Model.AppPermissions, options)
    |> deserialize(:repositories, :list, GitHubV3RESTAPI.Model.Repository, options)
  end
end
