# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.IssueEventProjectCard do
  @moduledoc """
  Issue Event Project Card
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :id,
    :project_url,
    :project_id,
    :column_name,
    :previous_column_name
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :id => integer(),
          :project_url => String.t(),
          :project_id => integer(),
          :column_name => String.t(),
          :previous_column_name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.IssueEventProjectCard do
  def decode(value, _options) do
    value
  end
end
