# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.IssueSimplePullRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :merged_at,
    :diff_url,
    :html_url,
    :patch_url,
    :url
  ]

  @type t :: %__MODULE__{
          :merged_at => DateTime.t() | nil,
          :diff_url => String.t() | nil,
          :html_url => String.t() | nil,
          :patch_url => String.t() | nil,
          :url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.IssueSimplePullRequest do
  def decode(value, _options) do
    value
  end
end
