# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.IssueComment do
  @moduledoc """
  Comments provide a way for people to collaborate on an issue.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :body,
    :body_text,
    :body_html,
    :html_url,
    :user,
    :created_at,
    :updated_at,
    :issue_url,
    :author_association,
    :performed_via_github_app,
    :reactions
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :body => String.t() | nil,
          :body_text => String.t() | nil,
          :body_html => String.t() | nil,
          :html_url => String.t(),
          :user => SimpleUser | nil,
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :issue_url => String.t(),
          :author_association => GitHubV3RESTAPI.Model.AuthorAssociation.t(),
          :performed_via_github_app => Integration | nil,
          :reactions => GitHubV3RESTAPI.Model.ReactionRollup.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.IssueComment do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:user, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:author_association, :struct, GitHubV3RESTAPI.Model.AuthorAssociation, options)
    |> deserialize(:performed_via_github_app, :struct, GitHubV3RESTAPI.Model.Integration, options)
    |> deserialize(:reactions, :struct, GitHubV3RESTAPI.Model.ReactionRollup, options)
  end
end
