# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.IssueEvent do
  @moduledoc """
  Issue Event
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :actor,
    :event,
    :commit_id,
    :commit_url,
    :created_at,
    :issue,
    :label,
    :assignee,
    :assigner,
    :review_requester,
    :requested_reviewer,
    :requested_team,
    :dismissed_review,
    :milestone,
    :project_card,
    :rename,
    :author_association,
    :lock_reason,
    :performed_via_github_app
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :actor => SimpleUser | nil,
          :event => String.t(),
          :commit_id => String.t() | nil,
          :commit_url => String.t() | nil,
          :created_at => DateTime.t(),
          :issue => GitHubV3RESTAPI.Model.IssueSimple.t() | nil,
          :label => GitHubV3RESTAPI.Model.IssueEventLabel.t() | nil,
          :assignee => SimpleUser | nil,
          :assigner => SimpleUser | nil,
          :review_requester => SimpleUser | nil,
          :requested_reviewer => SimpleUser | nil,
          :requested_team => GitHubV3RESTAPI.Model.Team.t() | nil,
          :dismissed_review => GitHubV3RESTAPI.Model.IssueEventDismissedReview.t() | nil,
          :milestone => GitHubV3RESTAPI.Model.IssueEventMilestone.t() | nil,
          :project_card => GitHubV3RESTAPI.Model.IssueEventProjectCard.t() | nil,
          :rename => GitHubV3RESTAPI.Model.IssueEventRename.t() | nil,
          :author_association => GitHubV3RESTAPI.Model.AuthorAssociation.t() | nil,
          :lock_reason => String.t() | nil,
          :performed_via_github_app => Integration | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.IssueEvent do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actor, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:issue, :struct, GitHubV3RESTAPI.Model.IssueSimple, options)
    |> deserialize(:label, :struct, GitHubV3RESTAPI.Model.IssueEventLabel, options)
    |> deserialize(:assignee, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:assigner, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:review_requester, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:requested_reviewer, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:requested_team, :struct, GitHubV3RESTAPI.Model.Team, options)
    |> deserialize(
      :dismissed_review,
      :struct,
      GitHubV3RESTAPI.Model.IssueEventDismissedReview,
      options
    )
    |> deserialize(:milestone, :struct, GitHubV3RESTAPI.Model.IssueEventMilestone, options)
    |> deserialize(:project_card, :struct, GitHubV3RESTAPI.Model.IssueEventProjectCard, options)
    |> deserialize(:rename, :struct, GitHubV3RESTAPI.Model.IssueEventRename, options)
    |> deserialize(:author_association, :struct, GitHubV3RESTAPI.Model.AuthorAssociation, options)
    |> deserialize(:performed_via_github_app, :struct, GitHubV3RESTAPI.Model.Integration, options)
  end
end
