# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Label do
  @moduledoc """
  Color-coded labels help you categorize and filter your issues (just like labels in Gmail).
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :name,
    :description,
    :color,
    :default
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :name => String.t(),
          :description => String.t() | nil,
          :color => String.t(),
          :default => boolean()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Label do
  def decode(value, _options) do
    value
  end
end
