# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.License do
  @moduledoc """
  License
  """

  @derive [Poison.Encoder]
  defstruct [
    :key,
    :name,
    :spdx_id,
    :url,
    :node_id,
    :html_url,
    :description,
    :implementation,
    :permissions,
    :conditions,
    :limitations,
    :body,
    :featured
  ]

  @type t :: %__MODULE__{
          :key => String.t(),
          :name => String.t(),
          :spdx_id => String.t() | nil,
          :url => String.t() | nil,
          :node_id => String.t(),
          :html_url => String.t(),
          :description => String.t(),
          :implementation => String.t(),
          :permissions => [String.t()],
          :conditions => [String.t()],
          :limitations => [String.t()],
          :body => String.t(),
          :featured => boolean()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.License do
  def decode(value, _options) do
    value
  end
end
