# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.LicenseSimple do
  @moduledoc """
  License Simple
  """

  @derive [Poison.Encoder]
  defstruct [
    :key,
    :name,
    :url,
    :spdx_id,
    :node_id,
    :html_url
  ]

  @type t :: %__MODULE__{
          :key => String.t(),
          :name => String.t(),
          :url => String.t() | nil,
          :spdx_id => String.t() | nil,
          :node_id => String.t(),
          :html_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.LicenseSimple do
  def decode(value, _options) do
    value
  end
end
