# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.LinkWithType do
  @moduledoc """
  Hypermedia Link with Type
  """

  @derive [Poison.Encoder]
  defstruct [
    :href,
    :type
  ]

  @type t :: %__MODULE__{
          :href => String.t(),
          :type => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.LinkWithType do
  def decode(value, _options) do
    value
  end
end
