# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Migration do
  @moduledoc """
  A migration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :owner,
    :guid,
    :state,
    :lock_repositories,
    :exclude_attachments,
    :repositories,
    :url,
    :created_at,
    :updated_at,
    :node_id,
    :archive_url,
    :exclude
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :owner => SimpleUser | nil,
          :guid => String.t(),
          :state => String.t(),
          :lock_repositories => boolean(),
          :exclude_attachments => boolean(),
          :repositories => [GitHubV3RESTAPI.Model.Repository.t()],
          :url => String.t(),
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :node_id => String.t(),
          :archive_url => String.t() | nil,
          :exclude => [AnyType] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Migration do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:owner, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:repositories, :list, GitHubV3RESTAPI.Model.Repository, options)
    |> deserialize(:exclude, :list, GitHubV3RESTAPI.Model.AnyType, options)
  end
end
