# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.OrgMembershipPermissions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :can_create_repository
  ]

  @type t :: %__MODULE__{
          :can_create_repository => boolean()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.OrgMembershipPermissions do
  def decode(value, _options) do
    value
  end
end
