# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.OrgHookConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :insecure_ssl,
    :content_type,
    :secret
  ]

  @type t :: %__MODULE__{
          :url => String.t() | nil,
          :insecure_ssl => String.t() | nil,
          :content_type => String.t() | nil,
          :secret => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.OrgHookConfig do
  def decode(value, _options) do
    value
  end
end
