# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.OrganizationFullPlan do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :space,
    :private_repos,
    :filled_seats,
    :seats
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :space => integer(),
          :private_repos => integer(),
          :filled_seats => integer() | nil,
          :seats => integer() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.OrganizationFullPlan do
  def decode(value, _options) do
    value
  end
end
