# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.OrganizationInvitation do
  @moduledoc """
  Organization Invitation
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :login,
    :email,
    :role,
    :created_at,
    :failed_at,
    :failed_reason,
    :inviter,
    :team_count,
    :node_id,
    :invitation_teams_url
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :login => String.t() | nil,
          :email => String.t() | nil,
          :role => String.t(),
          :created_at => String.t(),
          :failed_at => String.t() | nil,
          :failed_reason => String.t() | nil,
          :inviter => GitHubV3RESTAPI.Model.SimpleUser.t() | nil,
          :team_count => integer(),
          :node_id => String.t(),
          :invitation_teams_url => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.OrganizationInvitation do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:inviter, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
  end
end
