# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.PackagesBillingUsage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_gigabytes_bandwidth_used,
    :total_paid_gigabytes_bandwidth_used,
    :included_gigabytes_bandwidth
  ]

  @type t :: %__MODULE__{
          :total_gigabytes_bandwidth_used => integer(),
          :total_paid_gigabytes_bandwidth_used => integer(),
          :included_gigabytes_bandwidth => integer()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.PackagesBillingUsage do
  def decode(value, _options) do
    value
  end
end
