# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.PageBuild do
  @moduledoc """
  Page Build
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :status,
    :error,
    :pusher,
    :commit,
    :duration,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :status => String.t(),
          :error => GitHubV3RESTAPI.Model.PageBuildError.t(),
          :pusher => SimpleUser | nil,
          :commit => String.t(),
          :duration => integer(),
          :created_at => DateTime.t(),
          :updated_at => DateTime.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.PageBuild do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:error, :struct, GitHubV3RESTAPI.Model.PageBuildError, options)
    |> deserialize(:pusher, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
  end
end
