# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.PendingDeploymentReviewers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :reviewer
  ]

  @type t :: %__MODULE__{
          :type => GitHubV3RESTAPI.Model.DeploymentReviewerType.t() | nil,
          :reviewer => AnyOfsimpleUserteam | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.PendingDeploymentReviewers do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, GitHubV3RESTAPI.Model.DeploymentReviewerType, options)
    |> deserialize(:reviewer, :struct, GitHubV3RESTAPI.Model.AnyOfsimpleUserteam, options)
  end
end
