# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.PorterLargeFile do
  @moduledoc """
  Porter Large File
  """

  @derive [Poison.Encoder]
  defstruct [
    :ref_name,
    :path,
    :oid,
    :size
  ]

  @type t :: %__MODULE__{
          :ref_name => String.t(),
          :path => String.t(),
          :oid => String.t(),
          :size => integer()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.PorterLargeFile do
  def decode(value, _options) do
    value
  end
end
