# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.PullRequestSimpleLabels do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :name,
    :description,
    :color,
    :default
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :node_id => String.t() | nil,
          :url => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :color => String.t() | nil,
          :default => boolean() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.PullRequestSimpleLabels do
  def decode(value, _options) do
    value
  end
end
