# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.PullRequestMinimalHeadRepo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :url,
    :name
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :url => String.t(),
          :name => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.PullRequestMinimalHeadRepo do
  def decode(value, _options) do
    value
  end
end
