# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.RenamedIssueEvent do
  @moduledoc """
  Renamed Issue Event
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :actor,
    :event,
    :commit_id,
    :commit_url,
    :created_at,
    :performed_via_github_app,
    :rename
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :actor => GitHubV3RESTAPI.Model.SimpleUser.t() | nil,
          :event => String.t(),
          :commit_id => String.t() | nil,
          :commit_url => String.t() | nil,
          :created_at => String.t(),
          :performed_via_github_app => GitHubV3RESTAPI.Model.Integration.t() | nil,
          :rename => GitHubV3RESTAPI.Model.RenamedIssueEventRename.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.RenamedIssueEvent do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actor, :struct, GitHubV3RESTAPI.Model.SimpleUser, options)
    |> deserialize(:performed_via_github_app, :struct, GitHubV3RESTAPI.Model.Integration, options)
    |> deserialize(:rename, :struct, GitHubV3RESTAPI.Model.RenamedIssueEventRename, options)
  end
end
