# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ReviewCommentLinks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :self,
    :html,
    :pull_request
  ]

  @type t :: %__MODULE__{
          :self => GitHubV3RESTAPI.Model.Link.t(),
          :html => GitHubV3RESTAPI.Model.Link.t(),
          :pull_request => GitHubV3RESTAPI.Model.Link.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ReviewCommentLinks do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:self, :struct, GitHubV3RESTAPI.Model.Link, options)
    |> deserialize(:html, :struct, GitHubV3RESTAPI.Model.Link, options)
    |> deserialize(:pull_request, :struct, GitHubV3RESTAPI.Model.Link, options)
  end
end
