# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.RunnerApplication do
  @moduledoc """
  Runner Application
  """

  @derive [Poison.Encoder]
  defstruct [
    :os,
    :architecture,
    :download_url,
    :filename,
    :temp_download_token,
    :sha256_checksum
  ]

  @type t :: %__MODULE__{
          :os => String.t(),
          :architecture => String.t(),
          :download_url => String.t(),
          :filename => String.t(),
          :temp_download_token => String.t() | nil,
          :sha256_checksum => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.RunnerApplication do
  def decode(value, _options) do
    value
  end
end
