# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.RunnerGroupsOrg do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :visibility,
    :default,
    :selected_repositories_url,
    :runners_url,
    :inherited,
    :inherited_allows_public_repositories,
    :allows_public_repositories
  ]

  @type t :: %__MODULE__{
          :id => float(),
          :name => String.t(),
          :visibility => String.t(),
          :default => boolean(),
          :selected_repositories_url => String.t() | nil,
          :runners_url => String.t(),
          :inherited => boolean(),
          :inherited_allows_public_repositories => boolean() | nil,
          :allows_public_repositories => boolean()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.RunnerGroupsOrg do
  def decode(value, _options) do
    value
  end
end
