# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Runner do
  @moduledoc """
  A self hosted runner
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :os,
    :status,
    :busy,
    :labels
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :name => String.t(),
          :os => String.t(),
          :status => String.t(),
          :busy => boolean(),
          :labels => [GitHubV3RESTAPI.Model.RunnerLabels.t()]
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Runner do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:labels, :list, GitHubV3RESTAPI.Model.RunnerLabels, options)
  end
end
