# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ScimGroupListEnterpriseMembers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :"$ref",
    :display
  ]

  @type t :: %__MODULE__{
          :value => String.t() | nil,
          :"$ref" => String.t() | nil,
          :display => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ScimGroupListEnterpriseMembers do
  def decode(value, _options) do
    value
  end
end
