# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.SelectedActions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :github_owned_allowed,
    :verified_allowed,
    :patterns_allowed
  ]

  @type t :: %__MODULE__{
          :github_owned_allowed => boolean() | nil,
          :verified_allowed => boolean() | nil,
          :patterns_allowed => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.SelectedActions do
  def decode(value, _options) do
    value
  end
end
