# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.SimpleUser do
  @moduledoc """
  Simple User
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :email,
    :login,
    :id,
    :node_id,
    :avatar_url,
    :gravatar_id,
    :url,
    :html_url,
    :followers_url,
    :following_url,
    :gists_url,
    :starred_url,
    :subscriptions_url,
    :organizations_url,
    :repos_url,
    :events_url,
    :received_events_url,
    :type,
    :site_admin,
    :starred_at
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :email => String.t() | nil,
          :login => String.t(),
          :id => integer(),
          :node_id => String.t(),
          :avatar_url => String.t(),
          :gravatar_id => String.t() | nil,
          :url => String.t(),
          :html_url => String.t(),
          :followers_url => String.t(),
          :following_url => String.t(),
          :gists_url => String.t(),
          :starred_url => String.t(),
          :subscriptions_url => String.t(),
          :organizations_url => String.t(),
          :repos_url => String.t(),
          :events_url => String.t(),
          :received_events_url => String.t(),
          :type => String.t(),
          :site_admin => boolean(),
          :starred_at => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.SimpleUser do
  def decode(value, _options) do
    value
  end
end
