# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.SimpleCommitStatus do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :id,
    :node_id,
    :state,
    :context,
    :target_url,
    :required,
    :avatar_url,
    :url,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :description => String.t() | nil,
          :id => integer(),
          :node_id => String.t(),
          :state => String.t(),
          :context => String.t(),
          :target_url => String.t(),
          :required => boolean() | nil,
          :avatar_url => String.t() | nil,
          :url => String.t(),
          :created_at => DateTime.t(),
          :updated_at => DateTime.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.SimpleCommitStatus do
  def decode(value, _options) do
    value
  end
end
