# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.TeamProjectPermissions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :read,
    :write,
    :admin
  ]

  @type t :: %__MODULE__{
          :read => boolean(),
          :write => boolean(),
          :admin => boolean()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.TeamProjectPermissions do
  def decode(value, _options) do
    value
  end
end
