# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.TeamSimple do
  @moduledoc """
  Groups of organization members that gives permissions on specified repositories.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :members_url,
    :name,
    :description,
    :permission,
    :privacy,
    :html_url,
    :repositories_url,
    :slug,
    :ldap_dn
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :members_url => String.t(),
          :name => String.t(),
          :description => String.t() | nil,
          :permission => String.t(),
          :privacy => String.t() | nil,
          :html_url => String.t(),
          :repositories_url => String.t(),
          :slug => String.t(),
          :ldap_dn => String.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.TeamSimple do
  def decode(value, _options) do
    value
  end
end
