# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.Thread do
  @moduledoc """
  Thread
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :repository,
    :subject,
    :reason,
    :unread,
    :updated_at,
    :last_read_at,
    :url,
    :subscription_url
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :repository => GitHubV3RESTAPI.Model.MinimalRepository.t(),
          :subject => GitHubV3RESTAPI.Model.ThreadSubject.t(),
          :reason => String.t(),
          :unread => boolean(),
          :updated_at => String.t(),
          :last_read_at => String.t() | nil,
          :url => String.t(),
          :subscription_url => String.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.Thread do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:repository, :struct, GitHubV3RESTAPI.Model.MinimalRepository, options)
    |> deserialize(:subject, :struct, GitHubV3RESTAPI.Model.ThreadSubject, options)
  end
end
