# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.TimelineCrossReferencedEventSource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :issue
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :issue => GitHubV3RESTAPI.Model.IssueSimple.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.TimelineCrossReferencedEventSource do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:issue, :struct, GitHubV3RESTAPI.Model.IssueSimple, options)
  end
end
