# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.UserMarketplacePurchase do
  @moduledoc """
  User Marketplace Purchase
  """

  @derive [Poison.Encoder]
  defstruct [
    :billing_cycle,
    :next_billing_date,
    :unit_count,
    :on_free_trial,
    :free_trial_ends_on,
    :updated_at,
    :account,
    :plan
  ]

  @type t :: %__MODULE__{
          :billing_cycle => String.t(),
          :next_billing_date => DateTime.t() | nil,
          :unit_count => integer() | nil,
          :on_free_trial => boolean(),
          :free_trial_ends_on => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil,
          :account => GitHubV3RESTAPI.Model.MarketplaceAccount.t(),
          :plan => GitHubV3RESTAPI.Model.MarketplaceListingPlan.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.UserMarketplacePurchase do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:account, :struct, GitHubV3RESTAPI.Model.MarketplaceAccount, options)
    |> deserialize(:plan, :struct, GitHubV3RESTAPI.Model.MarketplaceListingPlan, options)
  end
end
