# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.ValidationError do
  @moduledoc """
  Validation Error
  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :documentation_url,
    :errors
  ]

  @type t :: %__MODULE__{
          :message => String.t(),
          :documentation_url => String.t(),
          :errors => [GitHubV3RESTAPI.Model.ValidationErrorErrors.t()] | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.ValidationError do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errors, :list, GitHubV3RESTAPI.Model.ValidationErrorErrors, options)
  end
end
