# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.WorkflowUsageBillable do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :UBUNTU,
    :MACOS,
    :WINDOWS
  ]

  @type t :: %__MODULE__{
          :UBUNTU => GitHubV3RESTAPI.Model.WorkflowUsageBillableUbuntu.t() | nil,
          :MACOS => GitHubV3RESTAPI.Model.WorkflowUsageBillableUbuntu.t() | nil,
          :WINDOWS => GitHubV3RESTAPI.Model.WorkflowUsageBillableUbuntu.t() | nil
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.WorkflowUsageBillable do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:UBUNTU, :struct, GitHubV3RESTAPI.Model.WorkflowUsageBillableUbuntu, options)
    |> deserialize(:MACOS, :struct, GitHubV3RESTAPI.Model.WorkflowUsageBillableUbuntu, options)
    |> deserialize(:WINDOWS, :struct, GitHubV3RESTAPI.Model.WorkflowUsageBillableUbuntu, options)
  end
end
