# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Model.WorkflowUsage do
  @moduledoc """
  Workflow Usage
  """

  @derive [Poison.Encoder]
  defstruct [
    :billable
  ]

  @type t :: %__MODULE__{
          :billable => GitHubV3RESTAPI.Model.WorkflowUsageBillable.t()
        }
end

defimpl Poison.Decoder, for: GitHubV3RESTAPI.Model.WorkflowUsage do
  import GitHubV3RESTAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:billable, :struct, GitHubV3RESTAPI.Model.WorkflowUsageBillable, options)
  end
end
