image: registry.bukalapak.io/sre/gudang/build/docker:0.0.1

stages:
- test
- build

variables:
  POSTGRES_DB: opencov_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
 
test:
  stage: test
  image: bitwalker/alpine-elixir-phoenix:latest
  services:
    - postgres:latest
  before_script:
    - export MIX_ENV=test
    - apk --no-cache --update add postgresql-client yarn
    - yarn install
    - mix deps.get
    - cp config/config.sample.exs config/config.exs
    - cp config/local.sample.exs config/local.exs
    - mix ecto.setup
  script:
    - mix test
  tags:
    - bare-metal

build:
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  before_script:
    - cp config/config.sample.exs config/config.exs
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - cp config/config.sample.exs config/config.exs
    - cp config/local.sample.exs config/local.exs
    - make build push
  tags:
    - build-image-shared
