apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "opencov-postgres-sandbox"
  labels:
    project: opencov
    service: postgres
    env: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      project: opencov
      service: postgres
      env: sandbox
  template:
    metadata:
      labels:
        project: opencov
        service: postgres
        release: 'aacd7c5'
        env: sandbox
    spec:
      containers:
      - name: opencov-postgres
        image: postgres:alpine
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 1.5Gi
            cpu: 2
          requests:
            memory: 0.5Gi
            cpu: 1
