apiVersion: v1
kind: Service
metadata:
  labels:
    project: {{.config.projectName}}
    service: {{.service.name}}
    env: {{.environment.name}}
  name: {{.config.projectName}}-{{.service.name}}-{{.environment.name}}
  namespace: {{.variable.VAR_KUBE_NAMESPACE}}
spec:
  selector:
    project: {{.config.projectName}}
    service: {{.service.name}}
    env: {{.environment.name}}
  ports:
  - protocol: TCP
    port: {{.service.port}}
  type: NodePort
