# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule GitHubV3RESTAPI.Api.RateLimit do
  @moduledoc """
  API calls for all endpoints tagged `RateLimit`.
  """

  alias GitHubV3RESTAPI.Connection
  import GitHubV3RESTAPI.RequestBuilder

  @doc """
  Get rate limit status for the authenticated user
  **Note:** Accessing this endpoint does not count against your REST API rate limit.  **Note:** The `rate` object is deprecated. If you're writing new API client code or updating existing code, you should use the `core` object instead of the `rate` object. The `core` object contains the same information that is present in the `rate` object.

  ## Parameters

  - connection (GitHubV3RESTAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, GitHubV3RESTAPI.Model.RateLimitOverview.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec rate_limit_get(Tesla.Env.client(), keyword()) ::
          {:ok, nil}
          | {:ok, GitHubV3RESTAPI.Model.RateLimitOverview.t()}
          | {:ok, GitHubV3RESTAPI.Model.BasicError.t()}
          | {:error, Tesla.Env.t()}
  def rate_limit_get(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/rate_limit")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      {200, %GitHubV3RESTAPI.Model.RateLimitOverview{}},
      {304, false},
      {404, %GitHubV3RESTAPI.Model.BasicError{}}
    ])
  end
end
