name: Test and Build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        docker-compose run opencov sh -c "sleep 10 && sh /opencov/create_env.sh && mix ecto.setup"
